export enum SecurityErrorCode {
  AUTH_TOKEN_MISSING = "AUTH_001",
  AUTH_TOKEN_EXPIRED = "AUTH_002",
  AUTH_TOKEN_INVALID = "AUTH_003",
  AUTH_SESSION_REVOKED = "AUTH_004",
  TENANT_MEMBERSHIP_MISSING = "TENANT_001",
  TENANT_AGENCY_INACTIVE = "TENANT_002",
  PERMISSION_DENIED = "PERM_001",
  ENTITLEMENT_REQUIRED = "ENTITLEMENT_001",
  PLATFORM_ADMIN_REQUIRED = "PLATFORM_001",
  BILLING_ROLE_REQUIRED = "BILLING_001",
  TEAM_CAPACITY_EXCEEDED = "BILLING_002",
  RENEWAL_NOT_AVAILABLE = "BILLING_003",
}
